- id: fortitude
  name: fortitude
  description: "A fast Fortran linter"
  entry: fortitude check --force-exclude
  language: python
  files: \.(f90|f95|f03|f08|f18|f23|F90|F95|F03|F08|F18|F23|pf)$
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
