- id: fortitude
  name: fortitude
  description: "A fast Fortran linter"
  entry: fortitude check --force-exclude
  language: python
  types_or: [fortran]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
